# --------------------------------------
# GitHub Action Workflow creation test
#
# Version 1.0
#
# --------------------------------------

name: GitHubActions-Basics

on:
  push:
    branches:
      - main

jobs:  
  my-test:
    runs-on: ubuntu-latest

    steps:
      - name: Print Hello Message in testing
        run: echo "Hello World 1"

      - name: Run few commands
        run: |
          echo "Hello Message 1"
          echo "Hello Message 2"

  my-deploy:
    runs-on: ubuntu-latest
    needs: [my-test]          #need to successfully run 'my-test' job forst to run this current

    steps:
      - name: Print current date & time
        run: timedatectl
